language: node_js
sudo: false
dist: trusty
node_js:
  - '10'

services:
  - docker

cache:
  yarn: true
  directories:
    - 'node_modules'

install:
  - yarn
  - bash ./princexml/install.sh

script:
  - yarn test
  - yarn build

before_deploy:
  - yarn serve
  - sleep 5
  - prince --javascript --structured-log=quiet --page-margin 0 http://localhost:9000/docs/v2.1/zh-CN/all/ -o public/KubeSphere-v2.1.pdf
  - docker build -t kubesphere/docs.kubesphere.io .

deploy:
  provider: script
  script: bash docker_push
  on:
    branch: master
