language: node_js
sudo: false
dist: trusty
node_js:
  - '10'

services:
  - docker

cache:
  yarn: true
  directories:
    - 'node_modules'

install:
  - yarn

script:
  - yarn test
  - yarn build:ci

before_deploy:
  - bash ./princexml/install.sh
  - yarn build
  - docker build -t docs.kubesphere.io .

deploy:
  provider: script
  script: bash docker_push
  on:
    branch: release-2.1
